import {StatCard,ResultBadge} from '../../components/ui';
import { useEffect, useState } from 'react';
import { getExecution, type Execution } from './api';
import { calendarDays, dateLabel, difficultyLabels, durationLabel, getActivity, localDay, type Activity } from './activity';
import { ExecutionPanel } from './ExecutionPanel';
const ignoreDirty=()=>{};
export function ActivityLauncher({studentId,admin=false}:{studentId:string;admin?:boolean}){
 const [open,setOpen]=useState(false);
 return <section className="activity-launcher">{admin&&<div className="coach-overview"><span className="eyebrow">ACOMPANHAMENTO</span><h2>Treinos, frequência e evolução</h2><p>Consulte os últimos treinos e os feedbacks deste aluno.</p></div>}<button type="button" className="secondary" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{admin?'Acompanhamento e feedbacks':'Treinos realizados'}</button>{open&&<ExecutionActivity key={studentId} studentId={studentId} admin={admin}/>}</section>;
}
export function ExecutionActivity({studentId,admin=false,initialSection='history'}:{studentId:string;admin?:boolean;initialSection?:'history'|'calendar'|'stats'}){
 const [section,setSection]=useState<'history'|'calendar'|'stats'|'feedback'>(initialSection);const [filter,setFilter]=useState('all');
 const [month,setMonth]=useState(()=>localDay().slice(0,7));const [page,setPage]=useState(0);const [refresh,setRefresh]=useState(0);
 const [data,setData]=useState<Activity|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 const [selected,setSelected]=useState<string|null>(null);const [detail,setDetail]=useState<Execution|null>(null);const [detailError,setDetailError]=useState('');
 useEffect(()=>{let stopped=false;setLoading(true);setError('');setData(null);getActivity(studentId,month,page).then(value=>{if(!stopped)setData(value);}).catch(e=>{if(!stopped)setError((e as Error).message);}).finally(()=>{if(!stopped)setLoading(false);});return()=>{stopped=true;};},[studentId,month,page,refresh]);
 useEffect(()=>{let stopped=false;setDetail(null);setDetailError('');if(selected)getExecution(selected).then(value=>{if(!stopped){if(value.status==='in_progress')setDetailError('Este treino ainda está em andamento.');else setDetail(value);}}).catch(()=>{if(!stopped)setDetailError('Não foi possível abrir o registro. Volte e tente novamente.');});return()=>{stopped=true;};},[selected]);
 if(selected)return <section className="training-activity"><button type="button" className="text-button" onClick={()=>setSelected(null)}>Voltar ao histórico</button>{detail?<><p>Prescrição original · programação versão {detail.program_version} · treino versão {detail.workout_version}</p><ExecutionPanel key={detail.id} initial={detail} onExit={()=>setSelected(null)} onDirty={ignoreDirty} allowShare={!admin}/></>:detailError?<p role="alert">{detailError}</p>:<p role="status">Carregando prescrição histórica…</p>}</section>;
 const calendar=calendarDays(month);
 return <section className="training-activity" aria-label={admin?'Acompanhamento do aluno':'Histórico de treinos'}>
 <div className="program-heading"><h2>{admin?'Acompanhamento do aluno':'Treinos realizados'}</h2><button type="button" className="text-button" disabled={loading} onClick={()=>setRefresh(v=>v+1)}>Atualizar histórico</button></div>
 <p>{admin?'Resultados e feedbacks do aluno, com a prescrição preservada de cada treino.':'Cada treino conta sua história. Consulte aqui suas atividades e a prescrição daquele momento.'}</p>
 <nav className="activity-tabs" aria-label="Seções do acompanhamento">{([['history','Histórico'],['calendar','Frequência'],['stats','Progresso'],...(admin?[['feedback','Feedbacks'] as const]:[])] as const).map(([id,label])=><button key={id} type="button" aria-pressed={section===id} onClick={()=>setSection(id)}>{label}</button>)}</nav><label className="activity-month">Mês de atividade<input type="month" min="1900-01" max="2200-12" value={month} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value)){setMonth(e.target.value);setPage(0);}}}/></label>
 {loading?<p role="status">Carregando histórico…</p>:error?<p role="alert">{error}</p>:data&&<>
 <p className="activity-frequency"><strong>{data.stats.week} {data.stats.week===1?'treino realizado':'treinos realizados'} esta semana</strong> · {data.stats.month} no mês selecionado</p>
 <p className="activity-caption">Semana de segunda a domingo. Datas no horário de Brasília. Frequência sem cobrança por dias de descanso.</p>
 <div hidden={section!=='calendar'}><div className="activity-metrics"><StatCard label="Treinos no mês" value={data.stats.month}/><StatCard label="Concluídos no mês" value={data.stats.month_completed} tone="positive"/><StatCard label="Não concluídos no mês" value={data.stats.month_not_completed} tone="negative"/></div><div className="activity-calendar" aria-label={'Atividade em '+month}>
 {['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(day=><span className="calendar-heading" key={day}>{day}</span>)}
 {Array.from({length:calendar.offset},(_,i)=><span key={'blank'+i} aria-hidden="true"/>)}
 {Array.from({length:calendar.count},(_,i)=>{const day=month+'-'+String(i+1).padStart(2,'0');const activity=data.days.find(d=>d.day===day);return <div key={day} className={'calendar-day'+(activity?(activity.completed===activity.total?' has-activity completed':activity.completed>0?' has-activity mixed':' has-activity incomplete'):'')} aria-label={`${dateLabel(day)}: ${activity?.total??0} treinos, ${activity?.completed??0} concluídos`} title={`${activity?.total??0} treinos · ${activity?.completed??0} concluídos`}><span>{i+1}</span>{activity&&<small>{activity.completed===activity.total?'✓':activity.completed===0?'✕':'✓/✕'} {activity.total}</small>}</div>;})}
 </div><p>{data.stats.month_completed} {data.stats.month_completed===1?'concluído':'concluídos'} · {data.stats.month_not_completed} {data.stats.month_not_completed===1?'não concluído':'não concluídos'} no mês. Verde: concluído. Vermelho: não concluído. Duas cores: ambos no dia.</p></div>
 <section className="activity-stats" hidden={section!=='stats'}><h3>Estatísticas gerais</h3><div className="activity-metrics">
 {([['Frequência semanal',data.stats.week],['Treinos realizados',data.stats.total],['Concluídos',data.stats.completed],['Não concluídos',data.stats.not_completed],['Duração total',durationLabel(data.stats.duration_seconds)],['Duração média',data.stats.total?durationLabel(data.stats.average_seconds):'—']] as const).map(([label,value])=><StatCard key={label} label={label} value={value} tone={label==='Concluídos'?'positive':label==='Não concluídos'?'negative':'brand'}/>)}
 </div><div className="difficulty-distribution" aria-label="Distribuição de dificuldade">{([['Fácil',data.stats.easy],['Na média',data.stats.balanced],['Difícil',data.stats.hard]] as const).map(([label,count])=><div key={label}><span>{label}</span><meter min={0} max={Math.max(1,data.stats.easy+data.stats.balanced+data.stats.hard)} value={count} aria-label={label}/><strong>{count}</strong></div>)}</div><p>Dificuldade: {data.stats.easy} fáceis · {data.stats.balanced} na medida · {data.stats.hard} difíceis{data.stats.unrated>0?` · ${data.stats.unrated} sem avaliação`:''}.</p><p>Todos os registros finalizados são considerados, inclusive os não concluídos. A duração inclui intervalos.</p></section>
 <div hidden={section!=='history'&&section!=='feedback'}><h3>{admin?'Treinos e feedbacks':'Seu histórico'} · mais recentes primeiro</h3>
 {section==='feedback'&&!data.history.some(row=>row.feedback||row.difficulty)&&<p>Nenhum feedback nesta página do histórico.</p>}<div className="history-filters"><span>Filtrar resultados desta página</span>{([['all','Todos'],['completed','Concluídos'],['not_completed','Não concluídos']] as const).map(([id,label])=><button type="button" key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div>{data.history.length>0&&!data.history.some(row=>filter==='all'||(filter==='not_completed'?row.status!=='completed':row.status==='completed'))&&<p>Nenhum registro com este filtro nesta página.</p>}{data.history.length===0?<div className="empty"><p>{data.stats.total===0?'Nenhum treino finalizado ainda.':'Não há registros nesta página.'}</p></div>:data.history.filter(row=>(section!=='feedback'||row.feedback||row.difficulty)&&(filter==='all'||(filter==='not_completed'?row.status!=='completed':row.status==='completed'))).map(row=>{
 const daysAgo=(Date.parse(data.today+'T12:00:00Z')-Date.parse(localDay(new Date(row.ended_at))+'T12:00:00Z'))/86400000;const recent=admin&&daysAgo>=0&&daysAgo<7;
 return <article className="activity-row" key={row.id}><div className="program-heading"><h4>{row.label} · {row.workout_name}</h4><ResultBadge completed={row.status==='completed'}/></div>
 <p>{dateLabel(row.performed_on)} · {durationLabel(row.duration_seconds)}{row.difficulty?' · '+difficultyLabels[row.difficulty]:''}</p><p>{row.program_name}</p>
 {admin&&(row.difficulty||row.feedback)&&<div className="activity-feedback">{recent&&<span className="eyebrow">FEEDBACK RECENTE</span>}{row.feedback&&<p className="execution-comment">{row.feedback}</p>}</div>}
 <button type="button" className="text-button" onClick={()=>setSelected(row.id)}>Ver treino e prescrição original</button></article>;
 })}
 {data.stats.total>20&&<nav className="program-actions" aria-label="Páginas do histórico"><button type="button" className="secondary" disabled={page===0} onClick={()=>setPage(v=>v-1)}>Mais recentes</button><span>Página {page+1} de {Math.ceil(data.stats.total/20)}</span><button type="button" className="secondary" disabled={(page+1)*20>=data.stats.total} onClick={()=>setPage(v=>v+1)}>Mais antigos</button></nav>}
 </div></>}
 </section>;
}
