import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import { beforeAll, afterAll, it, expect } from 'vitest';
const db = new PGlite();
const coach = '00000000-0000-4000-8000-000000000001';
const student = '00000000-0000-4000-8000-000000000002';
const session = '00000000-0000-4000-8000-000000000003';
async function asUser(id: string, sql: string) {
  await db.exec(`set role authenticated; set request.jwt.claim.sub='${id}'; set request.jwt.claim.session_id='${session}';`);
  try { return await db.query(sql); } finally { await db.exec('reset role'); }
}
beforeAll(async () => {
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
    create schema storage;
    create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,metadata jsonb);
    alter table storage.objects enable row level security;
    grant usage on schema storage to authenticated,anon;
    grant select,insert,update,delete on storage.objects to authenticated,anon;
    create schema auth;
    create table auth.users(id uuid primary key,email text,encrypted_password text);
    create table auth.sessions(id uuid primary key,user_id uuid);
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    create function auth.jwt() returns jsonb language sql stable as $$select jsonb_build_object('session_id',current_setting('request.jwt.claim.session_id',true))$$;
    grant usage on schema auth to authenticated;
    insert into auth.users values('${coach}','coach@test.invalid','hash'),('${student}','student@test.invalid','hash');`);
  for (const file of ['202609230001_identity.sql','202609230002_students.sql','202609230003_username_access.sql','202609240004_exercises.sql','202609240005_exercise_images_video.sql']) {
    await db.exec(readFileSync(new URL('../supabase/migrations/' + file, import.meta.url), 'utf8'));
  }
  await db.exec(`insert into public.profiles(id,full_name,username,role,must_change_password) values
    ('${coach}','Coach','filipe','admin',false),('${student}','Student','student','student',false);
    insert into private.login_identities(user_id,auth_email) values('${coach}','coach@test.invalid');
    insert into auth.sessions values('${session}','${coach}');
    select public.register_app_session('${coach}','${session}',1);`);
}, 30000);
afterAll(() => db.close());
it('enforces admin access, atomic audit, validation, concurrency and session revocation', async () => {
  const create = `select public.save_exercise(null,' Supino ',' Peitoral ',' Halteres ',' Orientações ',null)`;
  await expect(asUser(student, create)).rejects.toThrow();
  await db.exec('set role anon');
  await expect(db.query('select * from public.exercises')).rejects.toThrow();
  await db.exec('reset role');
  await asUser(coach, create);
  const rows = (await asUser(coach, 'select * from public.exercises')).rows as {id:string;updated_at:Date;name:string}[];
  expect(rows).toHaveLength(1); expect(rows[0].name).toBe('Supino');
  expect((await asUser(student, 'select * from public.exercises')).rows).toEqual([]);
  expect((await asUser(student, 'select * from public.exercise_audit')).rows).toEqual([]);
  await expect(asUser(coach, "insert into public.exercises(name,muscle_group) values('Teste','Teste')")).rejects.toThrow();
  await expect(asUser(coach, "select public.save_exercise(null,'  ','Peitoral','','',null)")).rejects.toThrow();
  const {id} = rows[0];
  await asUser(coach, `select public.save_exercise('${id}','Supino inclinado','Peitoral','','Nova orientação',(select updated_at from public.exercises where id='${id}'))`);
  await expect(asUser(coach, `select public.save_exercise('${id}','Supino','Peitoral','','','2000-01-01')`)).rejects.toThrow();
  expect((await db.query('select action from public.exercise_audit order by id')).rows).toEqual([{action:'exercise.created'},{action:'exercise.updated'}]);
  await asUser(coach, `select public.save_exercise_details('${id}','Supino','Peitoral','','',(select updated_at from public.exercises where id='${id}'),'https://vimeo.com/123')`);
  expect((await asUser(coach,'select video_url from public.exercises')).rows).toEqual([{video_url:'https://vimeo.com/123'}]);
  await expect(asUser(student, `select public.save_exercise_details(null,'Teste','Peitoral','','',null,'https://youtube.com/watch?v=123')`)).rejects.toThrow();
  const oldVersion = (await db.query<{version:string}>(`select updated_at::text as version from public.exercises where id='${id}'`)).rows[0].version;
  const auditBeforeVideo = Number((await db.query<{n:number}>('select count(*) as n from public.exercise_audit')).rows[0].n);
  await asUser(coach, `select public.save_exercise_details('${id}','Supino','Peitoral','','','${oldVersion}','https://youtube.com/watch?v=456')`);
  expect(Number((await db.query<{n:number}>('select count(*) as n from public.exercise_audit')).rows[0].n)).toBe(auditBeforeVideo + 1);
  expect((await db.query<{version:string}>(`select updated_at::text as version from public.exercises where id='${id}'`)).rows[0].version).not.toBe(oldVersion);
  await expect(asUser(coach, `select public.save_exercise_details('${id}','Stale','Peitoral','','','${oldVersion}','https://vimeo.com/stale')`)).rejects.toThrow();
  expect((await db.query('select name,video_url from public.exercises')).rows).toEqual([{name:'Supino',video_url:'https://youtube.com/watch?v=456'}]);
  const countBefore = (await db.query('select count(*) from public.exercise_audit')).rows;
  await expect(asUser(coach, `select public.save_exercise_details('${id}','Supino','Peitoral','','',(select updated_at from public.exercises where id='${id}'),'javascript:alert(1)')`)).rejects.toThrow();
  expect((await db.query('select count(*) from public.exercise_audit')).rows).toEqual(countBefore);
  const path = `${id}/00000000-0000-4000-8000-000000000005.png`;
  const insertImage = `insert into storage.objects(bucket_id,name,metadata) values('exercise-images','${path}','{"mimetype":"image/png","size":100}')`;
  await expect(asUser(student,insertImage)).rejects.toThrow();
  await asUser(coach,insertImage);
  expect((await asUser(student,'select * from storage.objects')).rows).toEqual([]);
  await expect(asUser(coach,`select public.set_exercise_image('${id}','${path}',null,'2000-01-01')`)).rejects.toThrow();
  await asUser(coach,`select public.set_exercise_image('${id}','${path}',null,(select updated_at from public.exercises where id='${id}'))`);
  expect((await asUser(coach,'select image_path from public.exercises')).rows).toEqual([{image_path:path}]);
  await asUser(coach,`delete from storage.objects where name='${path}'`);
  expect((await db.query('select * from storage.objects')).rows).toHaveLength(1);
  const nextPath = `${id}/00000000-0000-4000-8000-000000000006.png`;
  await asUser(coach,insertImage.replace(path,nextPath));
  await asUser(coach,`select public.set_exercise_image('${id}','${nextPath}','${path}',(select updated_at from public.exercises where id='${id}'))`);
  await asUser(coach,`delete from storage.objects where name='${path}'`);
  expect((await db.query('select name from storage.objects')).rows).toEqual([{name:nextPath}]);
  const beforeRerun = (await db.query('select * from public.exercises')).rows;
  const auditBeforeRerun = (await db.query('select * from public.exercise_audit order by id')).rows;
  const migration = readFileSync(new URL('../supabase/migrations/202609240005_exercise_images_video.sql',import.meta.url),'utf8');
  await db.exec(migration);
  expect((await db.query('select * from public.exercises')).rows).toEqual(beforeRerun);
  expect((await db.query('select * from public.exercise_audit order by id')).rows).toEqual(auditBeforeRerun);
  expect((await db.query('select * from storage.buckets')).rows).toHaveLength(1);
  expect((await db.query('select name from storage.objects')).rows).toEqual([{name:nextPath}]);
  await db.exec("update storage.buckets set public=true where id='exercise-images'");
  await expect(db.exec(migration)).rejects.toThrow('incompatible settings');
  await db.exec('rollback');
  expect((await db.query('select public from storage.buckets')).rows).toEqual([{public:true}]);
  await db.exec("update storage.buckets set public=false where id='exercise-images'");
  await db.exec(`update public.profiles set must_change_password=true where id='${coach}'`);
  expect((await asUser(coach,'select * from public.exercises')).rows).toEqual([]);
  await expect(asUser(coach,create)).rejects.toThrow();
  await db.exec(`update public.profiles set must_change_password=false where id='${coach}'; delete from auth.sessions;`);
  await expect(asUser(coach,create)).rejects.toThrow();
  expect((await asUser(coach,'select * from public.exercises')).rows).toEqual([]);
});
