import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import { beforeAll, afterAll, it, expect } from 'vitest';
const db = new PGlite();
const coach = '00000000-0000-4000-8000-000000000001';
const student = '00000000-0000-4000-8000-000000000002';
const session = '00000000-0000-4000-8000-000000000003';
async function asUser(id: string, sql: string) {
  await db.exec(`set role authenticated; set request.jwt.claim.sub='${id}'; set request.jwt.claim.session_id='${id===student?'00000000-0000-4000-8000-000000000004':session}';`);
  try { return await db.query(sql); } finally { await db.exec('reset role'); }
}
beforeAll(async () => {
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
    create schema storage;
    create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,metadata jsonb);
    alter table storage.objects enable row level security;
    grant usage on schema storage to authenticated,anon;
    grant select,insert,update,delete on storage.objects to authenticated,anon;
    create schema auth;
    create table auth.users(id uuid primary key,email text,encrypted_password text);
    create table auth.sessions(id uuid primary key,user_id uuid);
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    create function auth.jwt() returns jsonb language sql stable as $$select jsonb_build_object('session_id',current_setting('request.jwt.claim.session_id',true))$$;
    grant usage on schema auth to authenticated;
    insert into auth.users values('${coach}','coach@test.invalid','hash'),('${student}','student@test.invalid','hash');`);
  for (const file of ['202609230001_identity.sql','202609230002_students.sql','202609230003_username_access.sql','202609240004_exercises.sql','202609240005_exercise_images_video.sql','202609240006_workout_editor.sql','202609240007_student_programs.sql']) {
    await db.exec(readFileSync(new URL('../supabase/migrations/' + file, import.meta.url), 'utf8'));
  }
  await db.exec(`insert into public.profiles(id,full_name,username,role,must_change_password) values
    ('${coach}','Coach','filipe','admin',false),('${student}','Student','student','student',false);
    insert into private.login_identities(user_id,auth_email) values('${coach}','coach@test.invalid');
    insert into auth.sessions values('${session}','${coach}');
    select public.register_app_session('${coach}','${session}',1);`);
}, 30000);
beforeAll(async()=>{
 await db.exec(`insert into public.students(id) values('${student}');
 insert into private.login_identities(user_id,auth_email) values('${student}','student@test.invalid');
 insert into auth.sessions values('00000000-0000-4000-8000-000000000004','${student}');
 select public.register_app_session('${student}','00000000-0000-4000-8000-000000000004',1);`);
});
afterAll(() => db.close());
it('atomically assigns, versions, replaces and ends programs while isolating students and preserving images', async()=>{
 const exercise='00000000-0000-4000-8000-000000000011',workout='00000000-0000-4000-8000-000000000020',item='00000000-0000-4000-8000-000000000030';
 const program='00000000-0000-4000-8000-000000000040',replacement='00000000-0000-4000-8000-000000000041';
 const entry='00000000-0000-4000-8000-000000000050',other='00000000-0000-4000-8000-000000000060';
 const path=exercise+'/00000000-0000-4000-8000-000000000099.png';
 await db.exec(`insert into storage.objects(bucket_id,name) values('exercise-images','${path}');
 insert into public.exercises(id,name,muscle_group,image_path) values('${exercise}','Supino','Peitoral','${path}');
 insert into auth.users values('${other}','other@test.invalid','hash');
 insert into public.profiles(id,full_name,username,role,must_change_password) values('${other}','Other','other','student',false);
 insert into public.students(id) values('${other}');`);
 await asUser(coach,`select public.save_workout('${workout}','Treino A','Controle','${JSON.stringify([{id:item,exercise_id:exercise,sets:3,repetitions:'10',rest_seconds:60,coach_notes:'Devagar'}])}',0)`);
 const entries=[{id:entry,label:'Treino A',workout_id:workout,workout_version:1}];
 const save=(id=program,version=0,rows=entries,owner=student)=>`select public.save_student_program('${id}','${owner}','Programa inicial','2026-10-01','${JSON.stringify(rows)}',${version})`;
 const transition=(id:string,version:number,action:string,old?:string,oldVersion?:number)=>`select public.transition_student_program('${id}',${version},'${action}',${old?`'${old}'`:'null'},${oldVersion??'null'})`;
 await expect(asUser(student,save())).rejects.toThrow();
 await asUser(coach,save());
 expect((await asUser(student,'select * from public.student_programs')).rows).toHaveLength(0);
 await asUser(coach,transition(program,1,'activate'));
 expect((await asUser(student,'select id,status,version from public.student_programs')).rows).toEqual([{id:program,status:'active',version:2}]);
 expect((await asUser(student,'select version from public.program_revisions')).rows).toEqual([{version:2}]);
 expect((await asUser(student,'select name from storage.objects')).rows).toEqual([{name:path}]);
 for(const table of ['workouts','workout_items','workout_revisions','program_audit'])expect((await asUser(student,`select * from public.${table}`)).rows).toHaveLength(0);
 await db.exec(`insert into private.login_identities(user_id,auth_email) values('${other}','other@test.invalid');insert into auth.sessions values('00000000-0000-4000-8000-000000000061','${other}');select public.register_app_session('${other}','00000000-0000-4000-8000-000000000061',1);`);
 await db.exec(`set role authenticated;set request.jwt.claim.sub='${other}';set request.jwt.claim.session_id='00000000-0000-4000-8000-000000000061';`);
 expect((await db.query('select * from public.student_programs')).rows).toHaveLength(0);
 expect((await db.query('select * from public.program_revisions')).rows).toHaveLength(0);
 expect((await db.query('select * from storage.objects')).rows).toHaveLength(0);await db.exec('reset role');
 const original=(await db.query(`select snapshot from public.program_revisions where program_id='${program}' and version=2`)).rows;
 await db.exec(`update public.exercises set name='Supino alterado',image_path=null where id='${exercise}'`);
 await expect(db.query(`delete from storage.objects where name='${path}'`)).rejects.toThrow();
 expect((await asUser(coach,`delete from storage.objects where name='${path}' returning id`)).rows).toHaveLength(0);
 expect((await asUser(coach,`select public.exercise_image_is_retained('${path}') as retained`)).rows).toEqual([{retained:true}]);
 await asUser(coach,save(program,2,[{...entries[0],label:'Treino B'}]));
 expect((await db.query(`select snapshot from public.program_revisions where program_id='${program}' and version=2`)).rows).toEqual(original);
 expect((await asUser(student,'select version from public.program_revisions')).rows).toEqual([{version:3}]);
 await expect(asUser(coach,save(program,2))).rejects.toThrow();
 await expect(asUser(coach,save(program,3,[]))).rejects.toThrow();
 expect((await db.query(`select version from public.student_programs where id='${program}'`)).rows).toEqual([{version:3}]);
 await asUser(coach,save(replacement,0,[{...entries[0],id:'00000000-0000-4000-8000-000000000051'}]));
 await expect(asUser(coach,transition(replacement,1,'activate'))).rejects.toThrow();
 await expect(asUser(coach,transition(replacement,1,'activate',program,2))).rejects.toThrow();
 expect((await db.query('select * from public.program_audit')).rows).toHaveLength(4);
 await asUser(coach,transition(replacement,1,'activate',program,3));
 expect((await asUser(student,'select id from public.student_programs')).rows).toEqual([{id:replacement}]);
 expect((await db.query(`select status,version from public.student_programs where id='${program}'`)).rows).toEqual([{status:'ended',version:4}]);
 await expect(asUser(coach,save(program,4))).rejects.toThrow();
 await expect(asUser(coach,transition(program,4,'activate',replacement,2))).rejects.toThrow();
 await db.exec(`update public.profiles set must_change_password=true where id='${student}'`);
 expect((await asUser(student,'select * from public.student_programs')).rows).toHaveLength(0);
 expect((await asUser(student,'select * from storage.objects')).rows).toHaveLength(0);
 await db.exec(`update public.profiles set must_change_password=false,active=false where id='${student}'`);
 expect((await asUser(student,'select * from public.program_revisions')).rows).toHaveLength(0);
 await expect(asUser(coach,save(replacement,2,[{...entries[0],id:'00000000-0000-4000-8000-000000000051'}]))).rejects.toThrow();
 await db.exec(`update public.profiles set active=true where id='${student}'; delete from auth.sessions where user_id='${student}'`);
 expect((await asUser(student,'select * from public.student_programs')).rows).toHaveLength(0);
 await expect(asUser(student,transition(replacement,2,'end'))).rejects.toThrow();
 await asUser(coach,transition(replacement,2,'end'));
 expect((await asUser(student,'select * from public.student_programs')).rows).toHaveLength(0);
 expect((await asUser(student,'select * from storage.objects')).rows).toHaveLength(0);
 expect((await db.query('select action from public.program_audit order by id')).rows.map((r:any)=>r.action)).toEqual(['program.created','program.activated','program.updated','program.created','program.replaced','program.activated','program.ended']);
 for(const table of ['student_programs','program_entries','program_revisions','program_audit','program_media'])await expect(asUser(coach,`delete from public.${table}`)).rejects.toThrow();
 await expect(asUser(coach,`select private.record_program('${program}','program.updated')`)).rejects.toThrow();
 await db.exec('set role anon');await expect(db.query('select * from public.student_programs')).rejects.toThrow();expect((await db.query('select * from storage.objects')).rows).toHaveLength(0);await db.exec('reset role');
});
it('rolls back missing media and invalid edits, preserves ordering and requires current administrator access',async()=>{
 const ex='00000000-0000-4000-8000-000000000080',w='00000000-0000-4000-8000-000000000081',item='00000000-0000-4000-8000-000000000082',p='00000000-0000-4000-8000-000000000083';
 const path=ex+'/00000000-0000-4000-8000-000000000084.png';
 await db.exec(`insert into storage.objects(bucket_id,name) values('exercise-images','${path}');insert into public.exercises(id,name,muscle_group,image_path) values('${ex}','Remada','Costas','${path}');`);
 const workout=(version:number)=>`select public.save_workout('${w}','Treino C','','${JSON.stringify([{id:item,exercise_id:ex,sets:3,repetitions:'12',rest_seconds:60,coach_notes:''}])}',${version})`;
 await asUser(coach,workout(0));
 await db.exec(`update public.exercises set image_path=null where id='${ex}'`);
 expect((await asUser(coach,`delete from storage.objects where name='${path}' returning id`)).rows).toHaveLength(1);
 const entries=[{id:'00000000-0000-4000-8000-000000000085',label:'Treino A',workout_id:w,workout_version:1},{id:'00000000-0000-4000-8000-000000000086',label:'Treino B',workout_id:w,workout_version:1}];
 const save=(version:number,rows=entries)=>`select public.save_student_program('${p}','${student}','Ciclo dois','2026-10-01','${JSON.stringify(rows)}',${version})`;
 await expect(asUser(coach,save(0))).rejects.toThrow('image is no longer available');
 for(const table of ['student_programs','program_entries','program_revisions','program_audit'])expect((await db.query(`select * from public.${table} where ${table==='student_programs'?'id':'program_id'}='${p}'`)).rows).toHaveLength(0);
 await asUser(coach,workout(1));entries.forEach(e=>e.workout_version=2);
 await asUser(coach,save(0));await asUser(coach,save(1,[entries[1],entries[0]]));
 expect((await db.query(`select label,position from public.program_entries where program_id='${p}' order by position`)).rows).toEqual([{label:'Treino B',position:1},{label:'Treino A',position:2}]);
 expect((await db.query<{snapshot:{entries:{label:string}[]}}>(`select snapshot from public.program_revisions where program_id='${p}' and version=1`)).rows[0].snapshot.entries[0].label).toBe('Treino A');
 await expect(asUser(coach,save(2,[entries[0],entries[0]]))).rejects.toThrow();
 expect((await db.query(`select version from public.student_programs where id='${p}'`)).rows).toEqual([{version:2}]);
 await db.exec(`update public.profiles set must_change_password=true where id='${coach}'`);
 await expect(asUser(coach,save(2))).rejects.toThrow();
 await db.exec(`update public.profiles set must_change_password=false,active=false where id='${coach}'`);
 await expect(asUser(coach,save(2))).rejects.toThrow();
 await db.exec(`update public.profiles set active=true where id='${coach}';delete from auth.sessions where user_id='${coach}'`);
 await expect(asUser(coach,save(2))).rejects.toThrow();
});
