import { useEffect,useRef,useState,type FormEvent } from 'react';
import { listWorkouts,type Workout } from '../workouts/api';
import { searchText } from '../exercises/api';
import { displayDate,getProgramRevision,listProgramRevisions,listPrograms,saveProgram,statusLabel,transitionProgram,type Entry,type Program,type ProgramRevision } from './api';
import { ProgramView } from './ProgramView';

function ProgramEditor({student,program,initial,onClose,onSaved}:{student:string;program?:Program;initial?:Entry[];onClose:()=>void;onSaved:()=>void}){
  const [target]=useState(()=>program?.id??crypto.randomUUID());const [name,setName]=useState(program?.name??'');const [start,setStart]=useState(program?.start_date??new Date().toLocaleDateString('en-CA'));
  const [entries,setEntries]=useState<Entry[]>(initial??[]);const [workouts,setWorkouts]=useState<Workout[]>([]);const [query,setQuery]=useState('');
  const [error,setError]=useState('');const [loadError,setLoadError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [retry,setRetry]=useState(0);const saving=useRef(false);
  useEffect(()=>{let stopped=false;setLoading(true);setLoadError('');listWorkouts().then(rows=>{if(!stopped)setWorkouts(rows);}).catch(()=>{if(!stopped)setLoadError('Não foi possível carregar os treinos.');}).finally(()=>{if(!stopped)setLoading(false);});return()=>{stopped=true;};},[retry]);
  async function submit(event:FormEvent){event.preventDefault();if(saving.current)return;saving.current=true;setBusy(true);setError('');try{await saveProgram(target,student,name,start,entries,program?.version??0);onSaved();}catch(failure){setError((failure as Error).message);}finally{saving.current=false;setBusy(false);}}
  function move(index:number,delta:number){setEntries(current=>{const next=[...current];[next[index],next[index+delta]]=[next[index+delta],next[index]];return next;});}
  return <section className="student-form"><h2>{program?'Editar programação':'Nova programação'}</h2><p>{program?.status==='active'?'Ao salvar, uma nova versão ficará disponível ao aluno. As anteriores serão preservadas.':'Salve como rascunho e confira os treinos antes de ativar para o aluno.'}</p><form onSubmit={submit}><fieldset className="form-grid" disabled={busy}><label>Nome da programação<input required minLength={2} maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label>Data de início<input required type="date" min="1900-01-01" max="2200-12-31" value={start} onChange={e=>setStart(e.target.value)}/></label></fieldset>
    <h3>Selecionar treinos</h3><label>Buscar treino para adicionar<input disabled={busy} value={query} onChange={e=>setQuery(e.target.value)}/></label>
    {loading?<p role="status">Carregando treinos…</p>:loadError?<><p role="alert">{loadError}</p><button className="secondary" type="button" onClick={()=>setRetry(v=>v+1)}>Tentar carregar treinos novamente</button></>:<div className="workout-library">{workouts.filter(w=>searchText(w.name).includes(searchText(query))).map(w=><button className="workout-library-item" type="button" disabled={busy||entries.length>=26} key={w.id} onClick={()=>setEntries(current=>[...current,{id:crypto.randomUUID(),label:`Treino ${String.fromCharCode(65+current.length)}`,workout_id:w.id,workout_version:w.version}])}><span>{w.name}<small>Versão {w.version}</small></span><span>Adicionar</span></button>)}{!workouts.length&&<p>Cadastre um treino antes de criar a programação.</p>}</div>}
    <h3>Ordem da programação</h3>{!entries.length&&<p>Adicione pelo menos um treino.</p>}{entries.map((entry,index)=>{
      const current=workouts.find(w=>w.id===entry.workout_id);
      return <fieldset className="workout-card" disabled={busy} key={entry.id}><legend>{index+1}. {current?.name??'Treino atribuído'} · versão {entry.workout_version}</legend><label>Identificação do treino<input required maxLength={80} value={entry.label} onChange={e=>setEntries(rows=>rows.map(row=>row.id===entry.id?{...row,label:e.target.value}:row))}/></label><div className="workout-order"><button type="button" disabled={busy||index===0} onClick={()=>move(index,-1)} aria-label={`Subir treino ${index+1}`}>Subir</button><button type="button" disabled={busy||index===entries.length-1} onClick={()=>move(index,1)} aria-label={`Descer treino ${index+1}`}>Descer</button><button type="button" onClick={()=>setEntries(rows=>rows.filter(row=>row.id!==entry.id))} aria-label={`Remover treino ${index+1}`}>Remover</button></div>{current&&current.version!==entry.workout_version&&<><p>Há uma versão mais recente na biblioteca. A versão atribuída será mantida até você escolher atualizá-la.</p><button type="button" className="secondary" onClick={()=>setEntries(rows=>rows.map(row=>row.id===entry.id?{...row,workout_version:current.version}:row))}>Usar versão {current.version}</button></>}</fieldset>;
    })}
    {error&&<p role="alert" className="feedback error">{error}</p>}<div className="form-actions"><button className="secondary" type="button" disabled={busy} onClick={()=>{if(window.confirm('Sair do editor sem salvar as alterações?'))onClose();}}>Cancelar</button><button className="primary" disabled={busy||!entries.length}>{busy?'Salvando…':program?'Salvar programação':'Salvar rascunho'}</button></div></form></section>;
}

export function ProgramManager({studentId,studentActive}:{studentId:string;studentActive:boolean}){
  const [rows,setRows]=useState<Program[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [revision,setRevision]=useState(0);const [busy,setBusy]=useState(false);
  const [editing,setEditing]=useState<{program?:Program;entries?:Entry[]}|null>(null);const [history,setHistory]=useState<{program:Program;revisions:ProgramRevision[]}|null>(null);
  const [confirm,setConfirm]=useState<{program:Program;action:'activate'|'end';active?:Program}|null>(null);const inFlight=useRef(false);
  useEffect(()=>{let stopped=false;setLoading(true);setError('');listPrograms(studentId).then(data=>{if(!stopped)setRows(data);}).catch(failure=>{if(!stopped)setError(failure.message);}).finally(()=>{if(!stopped)setLoading(false);});return()=>{stopped=true;};},[studentId,revision]);
  function refresh(){setEditing(null);setHistory(null);setConfirm(null);setRevision(v=>v+1);}
  async function open(program:Program,mode:'edit'|'history'){
    if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');
    try{if(mode==='edit'){const current=await getProgramRevision(program.id,program.version);setEditing({program,entries:current.snapshot.entries.map(({id,label,workout_id,workout_version})=>({id,label,workout_id,workout_version}))});}else setHistory({program,revisions:await listProgramRevisions(program.id)});}
    catch(failure){setError((failure as Error).message);}finally{inFlight.current=false;setBusy(false);}
  }
  async function execute(){if(!confirm||inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{await transitionProgram(confirm.program,confirm.action,confirm.active);setNotice(confirm.action==='end'?'Programação encerrada.':'Programação ativada para o aluno.');refresh();}catch(failure){setError((failure as Error).message);setConfirm(null);}finally{inFlight.current=false;setBusy(false);}}
  const active=rows.find(p=>p.status==='active');
  if(editing)return <ProgramEditor key={editing.program?.id??'new'} student={studentId} program={editing.program} initial={editing.entries} onClose={refresh} onSaved={()=>{setNotice('Programação salva.');refresh();}}/>;
  if(history)return <section className="program-manager"><button className="text-button" onClick={refresh}>Voltar às programações</button><h2>Versões de {history.program.name}</h2>{history.revisions.map(r=><details className="workout-card" key={r.version}><summary>Versão {r.version} · {statusLabel[r.snapshot.status]} · {r.snapshot.name}</summary><ProgramView snapshot={r.snapshot}/></details>)}</section>;
  return <section className="program-manager"><div className="program-heading"><h2>Programação de treinos</h2><button type="button" className="primary" disabled={busy||loading||!studentActive} onClick={()=>{setNotice('');setEditing({});}}>Nova programação</button></div><p>{loading?'Carregando…':error?'Atualize para confirmar a programação ativa.':active?`Ativa: ${active.name} · início ${displayDate(active.start_date)}`:'Nenhuma programação ativa.'}</p>{!studentActive&&<p>Reative o aluno e reabra o cadastro para criar, editar ou ativar programações.</p>}
    {notice&&<p role="status" className="notice">{notice}</p>}{error&&<div><p role="alert" className="feedback error">{error}</p><button type="button" className="secondary" disabled={busy} onClick={refresh}>Atualizar programações</button></div>}
    {confirm&&<div className="workout-card" role="region" aria-label="Confirmar alteração da programação"><p>{confirm.action==='end'?`Encerrar ${confirm.program.name}? Ela deixará de aparecer para o aluno.`:confirm.active?`Ativar ${confirm.program.name} e encerrar ${confirm.active.name}? As versões anteriores serão preservadas.`:`Ativar ${confirm.program.name} para o aluno? A programação ficará visível imediatamente, inclusive se a data de início for futura.`}</p><div className="workout-order"><button type="button" disabled={busy} onClick={()=>void execute()}>Confirmar {confirm.action==='end'?'encerramento':'ativação'}</button><button type="button" disabled={busy} onClick={()=>setConfirm(null)}>Cancelar operação</button></div></div>}
    {!loading&&rows.map(p=><article className="workout-list-row" key={p.id}><div><h3>{p.name}</h3><p>{statusLabel[p.status]} · início {displayDate(p.start_date)} · versão {p.version}</p></div><div className="program-actions">{p.status!=='ended'&&<button type="button" className="secondary" disabled={busy||!studentActive} onClick={()=>void open(p,'edit')}>Editar programação</button>}{p.status==='draft'&&<button type="button" className="secondary" disabled={busy||!studentActive} onClick={()=>setConfirm({program:p,action:'activate',active})}>{active?'Ativar e substituir atual':'Ativar'}</button>}{p.status==='active'&&<button type="button" className="secondary" disabled={busy} onClick={()=>setConfirm({program:p,action:'end'})}>Encerrar</button>}<button type="button" className="text-button" disabled={busy} onClick={()=>void open(p,'history')}>Ver versões</button></div></article>)}
  </section>;
}
