import type {Execution} from '../../src/modules/execution/api';
const start=new Date(Date.now()-2700000).toISOString();
export let session:Execution={id:'demo',student_id:'demo',program_id:'demo',program_version:2,workout_version:1,status:'in_progress',version:1,started_at:start,ended_at:null,summary:null,items:[],snapshot:{program_name:'Força e constância',program_start_date:'2026-09-01',entry:{id:'demo',position:1,label:'Treino A',workout_id:'demo',workout_version:1,workout:{name:'Peito e tríceps',instructions:'Respeite os intervalos e execute com controle.',items:[{id:'item',position:1,exercise_id:'demo',sets:4,repetitions:'8–10',rest_seconds:90,coach_notes:'Mantenha o movimento controlado.',exercise:{name:'Supino reto com halteres',instructions:'Apoie os pés no chão.',image_path:null,video_url:'https://www.youtube.com/watch?v=demo'}}]}}}};
export function requireSupabase(){return {storage:{from:()=>({download:async()=>({data:await (await fetch('/filipe-oficial.png')).blob(),error:null})})},from:(table:string)=>{const data=table==='sharing_brand'?{image_path:'institutional/demo.png',version:1}:table==='student_programs'?[{id:'demo',student_id:'demo',name:'Força e constância',start_date:'2026-09-01',status:'active',version:2,updated_at:start}]:table==='program_revisions'?{version:2,created_at:start,snapshot:{name:'Força e constância',start_date:'2026-09-01',status:'active',entries:[session.snapshot.entry]}}:null;const q:any={then:(resolve:any)=>Promise.resolve({data,error:null}).then(resolve)};for(const key of ['select','order','range','eq','limit','single','maybeSingle'])q[key]=()=>q;return q;},rpc:async(name:string,args:any)=>{
 if(name==='start_execution')return {data:'demo',error:null};
 if(name==='get_execution')return {data:session,error:null};
 if(name==='finish_execution_feedback'){session={...session,status:args.outcome,difficulty:args.perceived_difficulty,feedback:args.comment,ended_at:new Date().toISOString(),duration_seconds:2700,performed_on:'2026-09-25',version:2};return {data:'demo',error:null};}
 if(name==='execution_activity')return {error:null,data:{today:'2026-09-25',month:args.month_start,page:0,history:[{id:'demo',started_at:start,ended_at:new Date().toISOString(),performed_on:'2026-09-25',duration_seconds:2700,status:'completed',difficulty:'balanced',feedback:'Senti boa evolução hoje.',program_name:'Força e constância',workout_name:'Peito e tríceps',label:'Treino A',program_version:2,workout_version:1}],days:[{day:'2026-09-25',total:1,completed:1}],stats:{total:1,completed:1,not_completed:0,duration_seconds:2700,average_seconds:2700,week:1,month:1,month_completed:1,month_not_completed:0,easy:0,balanced:1,hard:0,unrated:0}}};
 throw new Error('Unexpected mock call '+name);
}};}
