import {useEffect,useState} from 'react';
import {Button,Card,PageHeader} from '../../components/ui';
import {getSharingBrand,getBrandPhoto,saveBrandPhoto,type SharingBrand} from './api';
export default function SharingSettings(){
 const [brand,setBrand]=useState<SharingBrand|null>(null),[url,setUrl]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let stopped=false;setBrand(null);setError('');getSharingBrand().then(b=>{if(!stopped)setBrand(b);}).catch(e=>{if(!stopped)setError(e.message);});return()=>{stopped=true;};},[refresh]);
 useEffect(()=>{let stopped=false,local='';setUrl('');if(brand?.image_path)getBrandPhoto(brand.image_path).then(blob=>{if(!stopped){local=URL.createObjectURL(blob);setUrl(local);}}).catch(e=>{if(!stopped)setError(e.message);});return()=>{stopped=true;if(local)URL.revokeObjectURL(local);};},[brand]);
 async function save(){if(!file||!brand||busy)return;setBusy(true);setError('');setNotice('');try{setBrand(await saveBrandPhoto(file,brand));setFile(null);setNotice('Foto institucional salva. Os próximos cards utilizarão esta imagem.');}catch(e){setError((e as Error).message);setBrand(null);}finally{setBusy(false);}}
 return <><PageHeader eyebrow="IDENTIDADE DA CONSULTORIA" title="Foto para compartilhamento" description="Uma assinatura discreta nos Stories dos alunos. A foto da tela de entrada permanece igual."/><Card>{url&&<img className="institutional-preview" src={url} alt="Foto institucional configurada"/>}<p>JPEG, PNG ou WebP, até 5 MB. Prefira uma foto vertical, com espaço ao redor do rosto.</p><label>Escolher foto<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||!brand} onChange={e=>setFile(e.target.files?.[0]??null)}/></label><div className="program-actions"><Button disabled={busy||!brand||!file} onClick={()=>void save()}>{busy?'Enviando…':brand?.image_path?'Substituir foto':'Enviar foto'}</Button><Button tone="neutral" disabled={busy} onClick={()=>{setNotice('');setRefresh(v=>v+1);}}>Atualizar configuração</Button></div>{notice&&<p role="status">{notice}</p>}{error&&<p className="feedback error" role="alert">{error}</p>}<p className="activity-caption">Apenas a foto atual é disponibilizada aos alunos autorizados. Fotos anteriores ficam guardadas para auditoria.</p></Card></>;
}
