import type {ButtonHTMLAttributes,HTMLAttributes,ReactNode} from 'react';
import {ArrowUpRight,CalendarDays,ChartNoAxesCombined,Dumbbell,Home,UserRound,History} from 'lucide-react';
export type Tone='brand'|'positive'|'negative'|'neutral';
export function Button({tone='brand',className='',type='button',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{tone?:Tone}){return <button type={type} className={`ui-button ui-button--${tone} ${className}`} {...props}/>;}
export function Card({className='',...props}:HTMLAttributes<HTMLDivElement>){return <div className={`ui-card ${className}`} {...props}/>;}
export function Badge({tone='neutral',children}:{tone?:Tone;children:ReactNode}){return <span className={`ui-badge ui-badge--${tone}`}>{children}</span>;}
export function StatCard({label,value,tone='brand',icon}:{label:string;value:ReactNode;tone?:Tone;icon?:ReactNode}){return <Card className={`stat-card stat-card--${tone}`}><span className="stat-caption">{icon}{label}</span><strong>{value}</strong></Card>;}
export function EmptyState({title,children}:{title:string;children?:ReactNode}){return <Card className="empty"><Dumbbell size={28} aria-hidden="true"/><h3>{title}</h3>{children&&<p>{children}</p>}</Card>;}
export function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <header className="ui-page-header"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</header>;}
export type StudentView='home'|'workouts'|'history'|'profile'|'progress'|'calendar';
export function BottomNavigation({value,onChange,disabled=false}:{value:StudentView;onChange:(view:StudentView)=>void;disabled?:boolean}){return <nav className="bottom-navigation" aria-label="Navegação do aluno">{([{id:'home',label:'Início',icon:Home},{id:'workouts',label:'Treinos',icon:Dumbbell},{id:'history',label:'Histórico',icon:History},{id:'profile',label:'Perfil',icon:UserRound}] as const).map(item=><button type="button" key={item.id} disabled={disabled} aria-current={value===item.id?'page':undefined} onClick={()=>onChange(item.id)}><item.icon size={21} aria-hidden="true"/><span>{item.label}</span></button>)}</nav>;}
export function QuickAccess({onChange}:{onChange:(view:StudentView)=>void}){return <div className="quick-access">{([{id:'workouts',label:'Meus treinos',note:'Sua programação',icon:Dumbbell},{id:'progress',label:'Meu progresso',note:'Cada passo conta',icon:ChartNoAxesCombined},{id:'calendar',label:'Calendário',note:'Sua frequência',icon:CalendarDays},{id:'history',label:'Histórico',note:'Treinos realizados',icon:History}] as const).map(item=><button type="button" key={item.id} className="quick-card" onClick={()=>onChange(item.id)}><item.icon size={23} aria-hidden="true"/><ArrowUpRight size={15} className="quick-arrow" aria-hidden="true"/><strong>{item.label}</strong><small>{item.note}</small></button>)}</div>;}

export function ResultBadge({completed}:{completed:boolean}){return <Badge tone={completed?'positive':'negative'}><span aria-hidden="true">{completed?'✓':'✕'}</span>{completed?'Concluído':'Não concluído'}</Badge>;}
